// <auto-generated />
namespace Membership2WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v6AddMovieClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v6AddMovieClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080455325_v6AddMovieClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
