// <auto-generated />
namespace Membership2WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v7AddAddDateInMovieClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v7AddAddDateInMovieClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080755244_v7AddAddDateInMovieClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
